# Generated by Django 5.1.5 on 2025-02-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_image_event_rsvped_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='event_images/default.jpg', upload_to='event_images/'),
        ),
    ]
